pipeline {
    agent {
        label 'java-only-agent'
    }
    stages {
        stage('Clone GitHub Repo') {
            steps {
                git url: 'https://github.com/Sameer-8080/Website-PRT-ORG'
            }
        }
    }
}
